blank_issues_enabled: false
contact_links:
  - name: Artifacts Fabric (Old)
    url: https://github.com/florensie/artifacts-fabric/issues
    about: For issues related to the Fabric version of Artifacts (for Minecraft 1.19.2 and earlier)
