modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/ochotonida/artifacts/issues"

[[mods]]
modId="artifacts"
version="${version}"
displayName="Artifacts"
displayURL="https://www.curseforge.com/minecraft/mc-mods/artifacts"
logoFile="logo.png"
authors="ochotonida"
description='''Adds various new powerful uncraftable items to make exploration a bit more interesting'''

[[mixins]]
config = 'artifacts-common.mixins.json'
[[mixins]]
config = 'artifacts-neoforge.mixins.json'

[[dependencies.artifacts]]
    modId = "neoforge"
    required = true
    versionRange = "[20,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.artifacts]]
    modId = "minecraft"
    required = true
    versionRange = "[1.20.4,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.artifacts]]
    modId = "accessories"
    required = true
    versionRange = "[0.0.2-alpha,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.artifacts]]
    modId = "expandability"
    required = true
    versionRange = "[9.0.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.artifacts]]
    modId = "cloth_config"
    required = true
    versionRange = "[11.0.99,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.artifacts]]
    modId = "architectury"
    required = true
    versionRange = "[9.0.8,)"
    ordering="NONE"
    side="BOTH"